name: Test
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        php: ["8.0", "8.1"]
        typo3: ["^11.5", ]
      include:
        - php: "8.1"
          typo3: "^12.0"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install the right version
        run: composer require "typo3/cms-core:${{ matrix.typo3 }}" "typo3/cms-frontend:${{ matrix.typo3 }}" --update-with-all-dependencies
# composer config minimum-stability ${{ matrix.stability }}

      - name: Unit Tests with phpunit
        run: composer run test:unit

      - name: Unit Tests with phpunit and clover
        run: composer run test:clover

      - name: Upload clover
        run: bash <(curl -s https://codecov.io/bash)
